language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn build
after_script:
  - echo Debug directory
  - ls -l
  - cd ./dist
  - echo Debug dist
  - ls -l
  - touch CNAME
  - echo hud.hlae.site > CNAME
  - git init
  - git config --global user.name "U_NAME"
  - git config --global user.email "U_EMAIL"
  - git add .
  - git commit -m 'Travis CI'
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
